[tool.poetry]
name = "pythoneda-artifact-infrastructure-base"
version = "0.0.1a1"
description = "Infrastructure layer for pythoneda-artifact-scope/base"
authors = ["rydnr <github@acm-sl.org>"]
readme = "README.md"
homepage = "https://github.com/pythoneda-artifact-scope-infrastructure/base"
packages = [{include = "pythonedaartifactinfrastructure"}]

[tool.poetry.dependencies]
python = "^3.8"
pythoneda-base = "^0.0.1a13"
pythoneda-artifact-base = "^0.0.1a1"
pythoneda-infrastructure-base = "^0.0.1a9"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
